service: serverless-bundle-test-with-alias

custom:
  bundle:
    aliases:
      - libs: libs
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handlers/handler.hello